# ── Datasource ──────────────────────────────────────────
spring.datasource.url=jdbc:postgresql://localhost:5433/tiklasat
spring.datasource.username=postgres
spring.datasource.password=dev
spring.datasource.driver-class-name=org.postgresql.Driver

# ── JPA / Hibernate ────────────────────────────────────
# Yeni baştan yazdığımız için veritabanı şemasını Hibernate oluştursun
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Sunucu Portu
server.port=8080
