-- =====================================================================
-- TıklaSat · V1 · Kimlik, Yetkilendirme ve Coğrafya
-- ---------------------------------------------------------------------
-- Kapsanan kurallar: BR-U-001..009, BR-S-001, BR-S-003, BR-S-008,
--                    BR-K-003, BR-K-005, BR-K-006, BR-L-005
-- Veritabanı       : PostgreSQL 16
-- =====================================================================

-- ---------------------------------------------------------------------
-- Eklentiler
-- ---------------------------------------------------------------------
-- citext: büyük/küçük harf duyarsız metin tipi.
-- E-posta karşılaştırmasında lower(email) sarmalayıcısına gerek bırakmaz;
-- böylece UNIQUE kısıtı ve index doğrudan çalışır (BR-U-001).
CREATE EXTENSION IF NOT EXISTS citext;

-- ---------------------------------------------------------------------
-- Ortak yardımcı: updated_at otomatik güncelleme
-- ---------------------------------------------------------------------
-- Hibernate @UpdateTimestamp ile de doldurulur; bu trigger elle
-- çalıştırılan UPDATE'lerde de değerin doğru kalmasını garanti eder.
CREATE OR REPLACE FUNCTION set_updated_at() RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- =====================================================================
-- COĞRAFYA
-- =====================================================================

-- Türkiye illeri. id = plaka kodu (BR-L-005).
CREATE TABLE cities (
    id    SMALLINT     PRIMARY KEY,
    name  VARCHAR(50)  NOT NULL,
    CONSTRAINT uq_cities_name  UNIQUE (name),
    CONSTRAINT ck_cities_plate CHECK (id BETWEEN 1 AND 81)
);

CREATE TABLE districts (
    id       INTEGER      PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    city_id  SMALLINT     NOT NULL,
    name     VARCHAR(60)  NOT NULL,
    CONSTRAINT fk_districts_city FOREIGN KEY (city_id)
        REFERENCES cities (id) ON DELETE RESTRICT,
    CONSTRAINT uq_districts_city_name UNIQUE (city_id, name)
);

CREATE INDEX ix_districts_city ON districts (city_id);

-- =====================================================================
-- ROLLER
-- =====================================================================

-- BR-U-002: ZİYARETÇİ burada YOKTUR.
-- Ziyaretçi, kimlik doğrulaması yapılmamış istektir; veri değildir.
-- Spring Security'de permitAll() ile ifade edilir.
CREATE TABLE roles (
    id          SMALLINT     PRIMARY KEY,
    code        VARCHAR(20)  NOT NULL,
    name        VARCHAR(50)  NOT NULL,
    description VARCHAR(200),
    CONSTRAINT uq_roles_code UNIQUE (code),
    CONSTRAINT ck_roles_code CHECK (code IN ('BUYER', 'SELLER', 'ADMIN', 'MODERATOR'))
);

-- =====================================================================
-- KULLANICILAR
-- =====================================================================

CREATE TABLE users (
    id                 UUID          PRIMARY KEY DEFAULT gen_random_uuid(),

    -- Kimlik
    email              CITEXT        NOT NULL,
    password_hash      TEXT          NOT NULL,   -- BR-S-001 · Argon2id çıktısı
    password_algo      VARCHAR(20)   NOT NULL DEFAULT 'ARGON2ID',
    full_name          VARCHAR(100)  NOT NULL,
    phone              VARCHAR(20),

    -- Doğrulama (BR-U-004, BR-U-005)
    email_verified_at  TIMESTAMPTZ,
    phone_verified_at  TIMESTAMPTZ,

    -- Durum (BR-U-007)
    status             VARCHAR(24)   NOT NULL DEFAULT 'PENDING_VERIFICATION',

    -- Konum
    city_id            SMALLINT,
    district_id        INTEGER,

    -- Denormalize puan özeti (kaynak: user_ratings, bkz. data-model.md İ-1)
    rating_avg         NUMERIC(3,2),
    rating_count       INTEGER       NOT NULL DEFAULT 0,

    -- KVKK rıza kaydı (BR-K-006)
    consent_version    VARCHAR(10),
    consent_at         TIMESTAMPTZ,
    consent_ip         INET,

    -- KVKK anonimleştirme (BR-K-003) · fiziksel silme YAPILMAZ
    anonymized_at      TIMESTAMPTZ,

    -- Oturum güvenliği (BR-S-003)
    last_login_at      TIMESTAMPTZ,
    locked_until       TIMESTAMPTZ,

    created_at         TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at         TIMESTAMPTZ   NOT NULL DEFAULT now(),
    version            BIGINT        NOT NULL DEFAULT 0,

    CONSTRAINT uq_users_email UNIQUE (email),

    CONSTRAINT fk_users_city FOREIGN KEY (city_id)
        REFERENCES cities (id) ON DELETE SET NULL,
    CONSTRAINT fk_users_district FOREIGN KEY (district_id)
        REFERENCES districts (id) ON DELETE SET NULL,

    -- BR-U-007
    CONSTRAINT ck_users_status CHECK (status IN (
        'PENDING_VERIFICATION', 'ACTIVE', 'SUSPENDED', 'BANNED', 'ANONYMIZED'
    )),

    CONSTRAINT ck_users_rating CHECK (
        (rating_avg IS NULL OR rating_avg BETWEEN 0 AND 5)
        AND rating_count >= 0
    ),

    -- BR-K-003: anonimleştirme gerçekten uygulandı mı?
    -- Durum ANONYMIZED ise telefon silinmiş ve zaman damgası konmuş olmalı.
    CONSTRAINT ck_users_anonymized CHECK (
        (status <> 'ANONYMIZED')
        OR (anonymized_at IS NOT NULL AND phone IS NULL)
    )
);

CREATE TRIGGER trg_users_updated_at
    BEFORE UPDATE ON users
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE INDEX ix_users_status   ON users (status);
CREATE INDEX ix_users_location ON users (city_id, district_id);

-- ---------------------------------------------------------------------
-- Kullanıcı-Rol (BR-U-003)
-- ---------------------------------------------------------------------
-- Çoktan-çoğa: bir kullanıcı aynı anda hem BUYER hem SELLER olabilir.
-- Ayrı "satıcı hesabı" kavramı yoktur.
CREATE TABLE user_roles (
    user_id     UUID         NOT NULL,
    role_id     SMALLINT     NOT NULL,
    granted_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    granted_by  UUID,

    PRIMARY KEY (user_id, role_id),

    CONSTRAINT fk_user_roles_user FOREIGN KEY (user_id)
        REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_user_roles_role FOREIGN KEY (role_id)
        REFERENCES roles (id) ON DELETE RESTRICT,
    CONSTRAINT fk_user_roles_granted_by FOREIGN KEY (granted_by)
        REFERENCES users (id) ON DELETE SET NULL
);

CREATE INDEX ix_user_roles_role ON user_roles (role_id);

-- =====================================================================
-- OTURUM VE DOĞRULAMA TOKEN'LARI
-- =====================================================================

-- BR-S-008 · Yenileme token'ı rotasyonu
-- Token'ın kendisi DEĞİL, SHA-256 özeti saklanır: veritabanı sızarsa
-- saldırgan token'ları doğrudan kullanamaz.
CREATE TABLE refresh_tokens (
    id              UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id         UUID         NOT NULL,
    token_hash      CHAR(64)     NOT NULL,   -- sha256 hex
    issued_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    expires_at      TIMESTAMPTZ  NOT NULL,
    revoked_at      TIMESTAMPTZ,
    replaced_by_id  UUID,                    -- rotasyon zinciri
    user_agent      VARCHAR(255),
    ip_address      INET,

    CONSTRAINT uq_refresh_tokens_hash UNIQUE (token_hash),
    CONSTRAINT fk_refresh_tokens_user FOREIGN KEY (user_id)
        REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_refresh_tokens_replaced_by FOREIGN KEY (replaced_by_id)
        REFERENCES refresh_tokens (id) ON DELETE SET NULL,
    CONSTRAINT ck_refresh_tokens_expiry CHECK (expires_at > issued_at)
);

CREATE INDEX ix_refresh_tokens_user ON refresh_tokens (user_id)
    WHERE revoked_at IS NULL;

-- Tek tablo, purpose ile ayrışır (BR-U-004)
CREATE TABLE verification_tokens (
    id           UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id      UUID         NOT NULL,
    purpose      VARCHAR(24)  NOT NULL,
    token_hash   CHAR(64)     NOT NULL,
    expires_at   TIMESTAMPTZ  NOT NULL,
    consumed_at  TIMESTAMPTZ,
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT uq_verification_tokens_hash UNIQUE (token_hash),
    CONSTRAINT fk_verification_tokens_user FOREIGN KEY (user_id)
        REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT ck_verification_tokens_purpose CHECK (purpose IN (
        'EMAIL_VERIFICATION', 'PASSWORD_RESET', 'PHONE_VERIFICATION'
    )),
    CONSTRAINT ck_verification_tokens_expiry CHECK (expires_at > created_at)
);

CREATE INDEX ix_verification_tokens_user ON verification_tokens (user_id, purpose)
    WHERE consumed_at IS NULL;

-- BR-S-003 · Kaba kuvvet tespiti
-- BIGSERIAL: yüksek hacimli, URL'de asla görünmeyen iç tablo.
-- BR-K-005: IP adresi kişisel veridir, 6 ay sonra temizlenir.
CREATE TABLE login_attempts (
    id            BIGINT       PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    email         CITEXT       NOT NULL,   -- var olmayan hesap denemeleri de kaydedilir
    user_id       UUID,
    ip_address    INET         NOT NULL,
    user_agent    VARCHAR(255),
    successful    BOOLEAN      NOT NULL,
    attempted_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT fk_login_attempts_user FOREIGN KEY (user_id)
        REFERENCES users (id) ON DELETE SET NULL
);

CREATE INDEX ix_login_attempts_ip    ON login_attempts (ip_address, attempted_at DESC);
CREATE INDEX ix_login_attempts_email ON login_attempts (email, attempted_at DESC);

-- =====================================================================
-- Yorumlar (veritabanı üzerinden dokümantasyon)
-- =====================================================================
COMMENT ON TABLE  users                 IS 'Platform kullanıcıları. Fiziksel silme yapılmaz; BR-K-003 uyarınca anonimleştirilir.';
COMMENT ON COLUMN users.password_hash   IS 'BR-S-001 · Argon2id çıktısı (algoritma parametrelerini de içerir)';
COMMENT ON COLUMN users.anonymized_at   IS 'BR-K-003 · Dolu ise kişisel alanlar maskelenmiştir';
COMMENT ON COLUMN users.rating_avg      IS 'Denormalize · kaynak user_ratings. Arama sorgusunda JOIN+AVG maliyetinden kaçınmak için.';
COMMENT ON TABLE  roles                 IS 'BR-U-002 · Sabit 4 rol. ZİYARETÇİ bir rol değil, kimlik doğrulamasının yokluğudur.';
COMMENT ON TABLE  user_roles            IS 'BR-U-003 · Çoktan-çoğa. Aynı kullanıcı hem alıcı hem satıcı olabilir.';
COMMENT ON COLUMN refresh_tokens.token_hash     IS 'BR-S-008 · Token''ın kendisi değil SHA-256 özeti saklanır';
COMMENT ON COLUMN refresh_tokens.replaced_by_id IS 'Rotasyon zinciri. Kullanılmış token tekrar sunulursa hırsızlık tespiti yapılır.';
COMMENT ON TABLE  login_attempts        IS 'BR-S-003 · Kaba kuvvet tespiti. BR-K-005 uyarınca 6 ay sonra temizlenir.';
