-- =====================================================================
-- TıklaSat · V4 · Açık Artırma, Teklif ve Artış Kademeleri
-- ---------------------------------------------------------------------
-- Kapsanan kurallar: BR-A-001..012, BR-B-001..013
-- ---------------------------------------------------------------------
-- ⚠ SİSTEMİN SICAK YOLU (hot path) BURASIDIR.
--   Bu dosyadaki her kısıt, eşzamanlılık davranışının bir parçasıdır.
--   Ayrıntılı akış: docs/02-design/concurrency-design.md
-- =====================================================================

-- =====================================================================
-- TEKLİF ARTIŞ KADEMELERİ (BR-B-003)
-- ---------------------------------------------------------------------
-- Sabit %5 kuralı yerine kademeli tablo kullanılır. Gerekçe:
-- 1.000.000 TL'lik bir üründe %5 → 50.000 TL sıçrama demektir ve
-- teklif akışını öldürür. Bkz. business-rules.md §D-1.
--
-- Kademeler KODDA DEĞİL BURADA durur → değişiklik için deploy gerekmez.
-- =====================================================================

CREATE TABLE bid_increment_tiers (
    id              SMALLINT       PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    min_amount      NUMERIC(15,2)  NOT NULL,   -- dahil
    max_amount      NUMERIC(15,2),             -- hariç · NULL = sonsuz
    increment_type  VARCHAR(10)    NOT NULL,
    increment_value NUMERIC(15,2)  NOT NULL,
    is_active       BOOLEAN        NOT NULL DEFAULT true,
    created_at      TIMESTAMPTZ    NOT NULL DEFAULT now(),

    CONSTRAINT ck_tiers_type CHECK (increment_type IN ('FIXED', 'PERCENTAGE')),
    CONSTRAINT ck_tiers_value CHECK (increment_value > 0),
    CONSTRAINT ck_tiers_min CHECK (min_amount >= 0),
    CONSTRAINT ck_tiers_range CHECK (max_amount IS NULL OR max_amount > min_amount),
    CONSTRAINT ck_tiers_percentage CHECK (
        increment_type <> 'PERCENTAGE' OR increment_value <= 100
    )
);

-- ÇAKIŞMA ENGELLEME KISITI
-- EXCLUDE, UNIQUE'in genelleştirilmiş hâlidir: UNIQUE "iki satır eşit olamaz"
-- der, EXCLUDE ise istenen operatörü kullanır. Burada && (aralıklar kesişiyor)
-- operatörüyle "iki aktif kademenin fiyat aralığı kesişemez" kuralı kurulur.
--
-- Olmasaydı (0-1000, 25 TL) ve (500-2000, 100 TL) birlikte eklenebilir;
-- 800 TL'lik fiyat İKİ kademeye birden düşer ve minimum teklif tutarı
-- sorgunun döndürdüğü satırın sırasına göre değişirdi.
--
-- '[)' → alt sınır dahil, üst sınır hariç. max_amount NULL ise aralık
-- yukarıdan sınırsızdır (numrange semantiği).
ALTER TABLE bid_increment_tiers
    ADD CONSTRAINT ex_tiers_no_overlap
    EXCLUDE USING gist (
        numrange(min_amount, max_amount, '[)') WITH &&
    ) WHERE (is_active);

-- =====================================================================
-- AÇIK ARTIRMA
-- ---------------------------------------------------------------------
-- listings ile 1—1. Ayrı tablo olmasının sebebi PERFORMANS DEĞİL,
-- KİLİT ÇEKİŞMESİDİR: PostgreSQL MVCC gereği bir satırı güncellerken
-- satırın TAMAMININ yeni sürümünü yazar. Tek tabloda birleştirilseydi
-- her teklif 3000 karakterlik açıklamayı ve tsvector'ü de yeniden yazardı.
-- Gerekçe: ADR-0003.
-- =====================================================================

CREATE TABLE auctions (
    id                  UUID           PRIMARY KEY DEFAULT gen_random_uuid(),
    listing_id          UUID           NOT NULL,

    -- Fiyatlar · NUMERIC kullanılır, FLOAT/DOUBLE ASLA (0.1+0.2 ≠ 0.3)
    start_price         NUMERIC(15,2)  NOT NULL,          -- BR-A-002 · görünür
    reserve_price       NUMERIC(15,2),                    -- BR-A-003 · GİZLİ
    current_price       NUMERIC(15,2)  NOT NULL,
    currency            CHAR(3)        NOT NULL DEFAULT 'TRY',

    -- Denormalize · teklif transaction'ının İÇİNDE güncellenir
    bid_count           INTEGER        NOT NULL DEFAULT 0,
    highest_bid_id      UUID,                             -- FK aşağıda eklenir (döngüsel)

    winner_user_id      UUID,                             -- BR-A-008

    -- Zamanlar · TIMESTAMPTZ, UTC (BR-A-011)
    starts_at           TIMESTAMPTZ    NOT NULL,
    ends_at             TIMESTAMPTZ    NOT NULL,          -- DEĞİŞKEN · sniper uzatır
    original_ends_at    TIMESTAMPTZ    NOT NULL,          -- DEĞİŞMEZ · denetim referansı
    extension_count     SMALLINT       NOT NULL DEFAULT 0,

    status              VARCHAR(28)    NOT NULL DEFAULT 'SCHEDULED',
    closed_at           TIMESTAMPTZ,

    -- İptal (BR-A-012)
    cancelled_by        UUID,
    cancellation_reason VARCHAR(500),

    created_at          TIMESTAMPTZ    NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ    NOT NULL DEFAULT now(),
    version             BIGINT         NOT NULL DEFAULT 0,   -- optimistik kilit (2. ağ)

    -- BR-A-001 · 1—1 ilişkiyi kuran kısıt
    CONSTRAINT uq_auctions_listing UNIQUE (listing_id),

    CONSTRAINT fk_auctions_listing FOREIGN KEY (listing_id)
        REFERENCES listings (id) ON DELETE RESTRICT,
    CONSTRAINT fk_auctions_winner FOREIGN KEY (winner_user_id)
        REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT fk_auctions_cancelled_by FOREIGN KEY (cancelled_by)
        REFERENCES users (id) ON DELETE SET NULL,

    -- ---- Fiyat kuralları ----
    CONSTRAINT ck_auctions_start_price CHECK (start_price > 0),          -- BR-A-002
    CONSTRAINT ck_auctions_reserve CHECK (                                -- BR-A-003
        reserve_price IS NULL OR reserve_price >= start_price
    ),
    CONSTRAINT ck_auctions_current_price CHECK (current_price >= start_price),
    CONSTRAINT ck_auctions_currency CHECK (currency = 'TRY'),
    CONSTRAINT ck_auctions_bid_count CHECK (bid_count >= 0),

    -- ---- Zaman kuralları ----
    CONSTRAINT ck_auctions_time_order CHECK (ends_at > starts_at),

    -- BR-A-004 · Süre sınırı SATICININ SEÇTİĞİ süreye uygulanır.
    -- ends_at uzatmalarla kaydığı için original_ends_at üzerinden denetlenir.
    CONSTRAINT ck_auctions_duration CHECK (
        original_ends_at - starts_at BETWEEN INTERVAL '1 hour' AND INTERVAL '14 days'
    ),

    -- BR-A-006 · SNIPER KORUMASI TAVANI — VERİTABANI SEVİYESİNDE
    -- Kodda hata olsa, biri elle UPDATE çalıştırsa bile bir açık artırma
    -- orijinal bitişinden 60 dakikadan fazla uzayamaz.
    -- "Sonsuza kadar uzayan artırma" senaryosu yapısal olarak imkânsızdır.
    CONSTRAINT ck_auctions_extension_window CHECK (
        ends_at >= original_ends_at
        AND ends_at <= original_ends_at + INTERVAL '60 minutes'
    ),
    CONSTRAINT ck_auctions_extension_count CHECK (extension_count BETWEEN 0 AND 20),

    -- ---- Durum kuralları ----
    CONSTRAINT ck_auctions_status CHECK (status IN (          -- BR-A-005
        'SCHEDULED', 'ACTIVE', 'ENDED_SOLD', 'ENDED_NO_BIDS',
        'ENDED_RESERVE_NOT_MET', 'CANCELLED'
    )),

    -- BR-A-008 · Kazanan ⟺ ENDED_SOLD (çift yönlü tutarlılık)
    CONSTRAINT ck_auctions_winner_consistency CHECK (
        (status = 'ENDED_SOLD') = (winner_user_id IS NOT NULL)
    ),

    -- BR-A-012 · İptalde gerekçe zorunlu
    CONSTRAINT ck_auctions_cancellation CHECK (
        status <> 'CANCELLED'
        OR (cancellation_reason IS NOT NULL AND cancelled_by IS NOT NULL)
    ),

    -- Kapanmış durumda closed_at dolu olmalı
    CONSTRAINT ck_auctions_closed_at CHECK (
        (status IN ('SCHEDULED', 'ACTIVE')) = (closed_at IS NULL)
    )
);

CREATE TRIGGER trg_auctions_updated_at
    BEFORE UPDATE ON auctions
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- BR-A-007 · KAPATMA İŞİNİN INDEX'İ · kısmi index
-- Zamanla milyonlarca kapanmış artırma birikir; index yalnızca AKTİF
-- olanları içerdiği için kapatma işi sistem büyüdükçe yavaşlamaz.
CREATE INDEX ix_auctions_closing
    ON auctions (ends_at)
    WHERE status = 'ACTIVE';

CREATE INDEX ix_auctions_status_ends ON auctions (status, ends_at DESC);
CREATE INDEX ix_auctions_winner ON auctions (winner_user_id)
    WHERE winner_user_id IS NOT NULL;

-- =====================================================================
-- TEKLİFLER
-- ---------------------------------------------------------------------
-- APPEND-ONLY: UPDATE bids SET amount = ... HİÇBİR KOŞULDA çalıştırılmaz.
-- Yalnızca status alanı değişir (BR-B-005). Gerekçeler:
--   · Verilen teklif bağlayıcıdır; geçmişe dönük değişmesi güveni yıkar
--   · Değişmez kayıt, dolandırıcılık incelemesinin tek güvenilir kanıtıdır
--   · INSERT'ler birbirini kilitlemez → eşzamanlılık avantajı
-- =====================================================================

CREATE TABLE bids (
    id           UUID           PRIMARY KEY DEFAULT gen_random_uuid(),
    auction_id   UUID           NOT NULL,
    bidder_id    UUID           NOT NULL,

    amount       NUMERIC(15,2)  NOT NULL,

    -- BR-B-013 · VEKİL TEKLİF HAZIRLIĞI
    -- v1'de max_amount her zaman NULL, is_proxy her zaman false.
    -- Kolonlar şimdi eklenir ki v2'de otomatik artırma özelliği
    -- migration gerektirmeden açılabilsin.
    max_amount   NUMERIC(15,2),
    is_proxy     BOOLEAN        NOT NULL DEFAULT false,

    status       VARCHAR(12)    NOT NULL DEFAULT 'WINNING',

    -- BR-B-012 · dolandırıcılık analizi için
    ip_address   INET,
    user_agent   VARCHAR(255),

    created_at   TIMESTAMPTZ    NOT NULL DEFAULT now(),

    -- Admin geçersizleştirmesi (BR-B-005) · satır SİLİNMEZ
    voided_by    UUID,
    voided_at    TIMESTAMPTZ,
    void_reason  VARCHAR(500),

    CONSTRAINT fk_bids_auction FOREIGN KEY (auction_id)
        REFERENCES auctions (id) ON DELETE RESTRICT,
    CONSTRAINT fk_bids_bidder FOREIGN KEY (bidder_id)
        REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT fk_bids_voided_by FOREIGN KEY (voided_by)
        REFERENCES users (id) ON DELETE SET NULL,

    -- ================================================================
    -- BR-B-004 · ÜÇ SAVUNMA KATMANININ İKİNCİSİ
    -- ----------------------------------------------------------------
    -- Bu basit görünen kısıt bir EŞZAMANLILIK SAVUNMASIDIR.
    -- Kilitleme mantığında bir hata olsa ve iki teklif aynı anda
    -- current_price=1000 görüp ikisi de 1100 yazmaya kalksa, veritabanı
    -- ikincisini REDDEDER. INSERT sırasındaki benzersizlik kontrolü
    -- PostgreSQL'de atomiktir; hiçbir yarış koşulu bunu atlatamaz.
    --
    -- Yani: kilit "kaybolan güncellemeyi" engeller; bu kısıt ise
    -- KİLİDİN KENDİSİ HATALIYSA devreye girer.
    -- ================================================================
    CONSTRAINT uq_bids_auction_amount UNIQUE (auction_id, amount),

    CONSTRAINT ck_bids_amount_positive CHECK (amount > 0),

    -- BR-B-013 · vekil teklifte tavan, verilen teklifin altında olamaz
    CONSTRAINT ck_bids_max_amount CHECK (max_amount IS NULL OR max_amount >= amount),
    CONSTRAINT ck_bids_proxy_consistency CHECK (
        is_proxy = false OR max_amount IS NOT NULL
    ),

    CONSTRAINT ck_bids_status CHECK (status IN (
        'WINNING', 'OUTBID', 'WON', 'LOST', 'VOIDED'
    )),

    -- BR-B-005 · geçersizleştirme kaydı eksiksiz olmalı
    CONSTRAINT ck_bids_void_consistency CHECK (
        (status = 'VOIDED') = (voided_at IS NOT NULL AND void_reason IS NOT NULL)
    )
);

-- Döngüsel yabancı anahtar: auctions.highest_bid_id → bids.id
-- bids tablosu artık var, kısıt şimdi eklenebilir.
ALTER TABLE auctions
    ADD CONSTRAINT fk_auctions_highest_bid FOREIGN KEY (highest_bid_id)
    REFERENCES bids (id) ON DELETE RESTRICT;

-- En yüksek teklif + teklif geçmişi (sıcak yol)
CREATE INDEX ix_bids_auction_amount  ON bids (auction_id, amount DESC);
-- "Son teklifler" akışı
CREATE INDEX ix_bids_auction_created ON bids (auction_id, created_at DESC);
-- "Tekliflerim" sayfası
CREATE INDEX ix_bids_bidder          ON bids (bidder_id, created_at DESC);

-- =====================================================================
-- SNIPER UZATMA DENETİM KAYDI (BR-A-006)
-- ---------------------------------------------------------------------
-- auctions.extension_count sadece "kaç kez uzadı" der. Bir kullanıcı
-- "artırma neden 20 dakika geç bitti?" diye itiraz ettiğinde bu tablo
-- her uzatmayı HANGİ TEKLİF yüzünden, hangi zamandan hangi zamana
-- yapıldığıyla satır satır gösterir.
-- =====================================================================

CREATE TABLE auction_extensions (
    id                UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
    auction_id        UUID         NOT NULL,
    bid_id            UUID         NOT NULL,   -- uzatmayı tetikleyen teklif
    extension_no      SMALLINT     NOT NULL,   -- 1'den başlar
    previous_ends_at  TIMESTAMPTZ  NOT NULL,
    new_ends_at       TIMESTAMPTZ  NOT NULL,
    created_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT fk_auction_ext_auction FOREIGN KEY (auction_id)
        REFERENCES auctions (id) ON DELETE RESTRICT,
    CONSTRAINT fk_auction_ext_bid FOREIGN KEY (bid_id)
        REFERENCES bids (id) ON DELETE RESTRICT,

    CONSTRAINT uq_auction_ext_no UNIQUE (auction_id, extension_no),
    CONSTRAINT ck_auction_ext_no CHECK (extension_no BETWEEN 1 AND 20),
    CONSTRAINT ck_auction_ext_forward CHECK (new_ends_at > previous_ends_at)
);

CREATE INDEX ix_auction_ext_auction ON auction_extensions (auction_id, extension_no);

-- =====================================================================
-- Yorumlar
-- =====================================================================
COMMENT ON TABLE  auctions                   IS 'Açık artırma mekanizması (SICAK veri). Her teklifte güncellenir — ADR-0003.';
COMMENT ON COLUMN auctions.reserve_price     IS 'BR-A-003 · GİZLİ taban. API yanıtlarında ASLA döndürülmez, yalnızca "ulaşıldı/ulaşılmadı" bilgisi verilir.';
COMMENT ON COLUMN auctions.ends_at           IS 'BR-A-006 · Sniper koruması ile değişir. Yeni değer = teklif_anı + 120sn.';
COMMENT ON COLUMN auctions.original_ends_at  IS 'Değişmez. Süre (BR-A-004) ve uzatma tavanı (BR-A-006) denetimlerinin referansı.';
COMMENT ON COLUMN auctions.version           IS 'JPA optimistik kilit. Teklif yolu pesimistik kilit kullanır; bu, teklif DIŞI güncellemeler için 2. güvenlik ağıdır.';
COMMENT ON TABLE  bids                       IS 'BR-B-005 · APPEND-ONLY. amount hiçbir koşulda UPDATE edilmez; iptal VOIDED statüsüyle yapılır.';
COMMENT ON COLUMN bids.max_amount            IS 'BR-B-013 · Vekil teklif hazırlığı. v1''de her zaman NULL.';
COMMENT ON TABLE  bid_increment_tiers        IS 'BR-B-003 · Kademeli artış. Kodda değil burada durur → değişiklik deploy gerektirmez.';
COMMENT ON TABLE  auction_extensions         IS 'BR-A-006 · Sniper uzatma denetim izi. Şeffaflık için her uzatma kaydedilir.';
