-- =====================================================================
-- TıklaSat · V5 · Bildirim, Outbox, Denetim ve Güven
-- ---------------------------------------------------------------------
-- Kapsanan kurallar: BR-N-001..007, BR-S-006, BR-K-004, BR-K-005
-- =====================================================================

-- =====================================================================
-- TRANSACTIONAL OUTBOX (BR-N-007)
-- ---------------------------------------------------------------------
-- Teklif kabul edildiğinde WebSocket yayınını DOĞRUDAN yapmak iki
-- şekilde bozulur:
--   (a) Yayın gitti ama transaction geri alındı
--       → kullanıcılar VAR OLMAYAN bir teklif gördü
--   (b) Transaction başarılı ama yayın kayboldu
--       → ekranlar DONUK kaldı, kimse yeni fiyatı görmedi
--
-- Outbox satırı teklifle AYNI TRANSACTION'DA yazılır: teklif varsa olay
-- da vardır, teklif yoksa olay da yoktur. Ayrı bir yayıncı süreç bu
-- satırları okuyup gönderir. Bildirim servisi çökse bile teklif kabulü
-- etkilenmez.
-- =====================================================================

CREATE TABLE outbox_events (
    -- BIGINT identity BİLİNÇLİDİR: olaylar üretim SIRASIYLA yayınlanmalıdır.
    -- UUID rastgele olduğu için sıra bilgisi taşımaz.
    id              BIGINT       PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,

    aggregate_type  VARCHAR(40)  NOT NULL,
    aggregate_id    UUID         NOT NULL,
    event_type      VARCHAR(50)  NOT NULL,
    payload         JSONB        NOT NULL,

    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    published_at    TIMESTAMPTZ,             -- NULL = henüz yayınlanmadı
    attempt_count   SMALLINT     NOT NULL DEFAULT 0,
    last_error      TEXT,

    CONSTRAINT ck_outbox_aggregate_type CHECK (aggregate_type IN (
        'AUCTION', 'LISTING', 'USER', 'BID'
    )),
    CONSTRAINT ck_outbox_event_type CHECK (event_type IN (
        'BID_PLACED', 'BID_VOIDED', 'USER_OUTBID',
        'AUCTION_EXTENDED', 'AUCTION_CLOSED', 'AUCTION_CANCELLED',
        'AUCTION_ENDING_SOON', 'LISTING_APPROVED', 'LISTING_REJECTED'
    )),
    CONSTRAINT ck_outbox_attempts CHECK (attempt_count >= 0)
);

-- KISMİ INDEX · yayıncının döngü sorgusu
-- Tablo milyonlarca satıra çıksa bile index yalnızca BEKLEYEN olayları
-- içerir (genelde birkaç düzine satır) → sorgu tablo büyüklüğünden
-- bağımsız olarak sabit hızda kalır.
CREATE INDEX ix_outbox_unpublished
    ON outbox_events (id)
    WHERE published_at IS NULL;

CREATE INDEX ix_outbox_aggregate
    ON outbox_events (aggregate_type, aggregate_id, id);

-- =====================================================================
-- BİLDİRİMLER (BR-N-001)
-- =====================================================================

CREATE TABLE notifications (
    id          UUID          PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id     UUID          NOT NULL,
    type        VARCHAR(32)   NOT NULL,
    title       VARCHAR(150)  NOT NULL,
    body        VARCHAR(500)  NOT NULL,
    payload     JSONB,                        -- derin bağlantı verisi
    listing_id  UUID,
    auction_id  UUID,
    read_at     TIMESTAMPTZ,
    created_at  TIMESTAMPTZ   NOT NULL DEFAULT now(),

    CONSTRAINT fk_notifications_user FOREIGN KEY (user_id)
        REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_notifications_listing FOREIGN KEY (listing_id)
        REFERENCES listings (id) ON DELETE SET NULL,
    CONSTRAINT fk_notifications_auction FOREIGN KEY (auction_id)
        REFERENCES auctions (id) ON DELETE SET NULL,

    CONSTRAINT ck_notifications_type CHECK (type IN (
        'OUTBID', 'AUCTION_WON', 'AUCTION_SOLD', 'AUCTION_CANCELLED',
        'ENDING_SOON', 'LISTING_APPROVED', 'LISTING_REJECTED',
        'RESERVE_NOT_MET', 'NO_BIDS'
    ))
);

-- KISMİ INDEX · "okunmamış bildirim rozeti" sorgusu
CREATE INDEX ix_notifications_unread
    ON notifications (user_id, created_at DESC)
    WHERE read_at IS NULL;

CREATE INDEX ix_notifications_user ON notifications (user_id, created_at DESC);

-- =====================================================================
-- TAKİP LİSTESİ (BR-N-002)
-- =====================================================================
-- Bileşik birincil anahtar · ayrı bir id kolonu gereksizdir.
CREATE TABLE watchlist (
    user_id     UUID         NOT NULL,
    listing_id  UUID         NOT NULL,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),

    PRIMARY KEY (user_id, listing_id),

    CONSTRAINT fk_watchlist_user FOREIGN KEY (user_id)
        REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_watchlist_listing FOREIGN KEY (listing_id)
        REFERENCES listings (id) ON DELETE CASCADE
);

-- "Bu ilanı takip edenlere bitiş uyarısı gönder" sorgusu
CREATE INDEX ix_watchlist_listing ON watchlist (listing_id);

-- =====================================================================
-- DENETİM KAYITLARI (BR-S-006)
-- ---------------------------------------------------------------------
-- BR-K-005 · 2 yıl sonra otomatik temizlenir.
-- =====================================================================

CREATE TABLE audit_logs (
    id             BIGINT       PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    actor_user_id  UUID,                      -- NULL = sistem
    action         VARCHAR(50)  NOT NULL,
    entity_type    VARCHAR(40)  NOT NULL,
    entity_id      UUID         NOT NULL,
    before_state   JSONB,
    after_state    JSONB,
    ip_address     INET,
    created_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT fk_audit_logs_actor FOREIGN KEY (actor_user_id)
        REFERENCES users (id) ON DELETE SET NULL,

    CONSTRAINT ck_audit_logs_action CHECK (action IN (
        'ROLE_GRANTED', 'ROLE_REVOKED',
        'LISTING_APPROVED', 'LISTING_REJECTED', 'LISTING_ARCHIVED',
        'AUCTION_CANCELLED', 'BID_VOIDED',
        'USER_SUSPENDED', 'USER_BANNED', 'USER_REACTIVATED', 'USER_ANONYMIZED',
        'SELF_BID_ATTEMPT', 'REPORT_RESOLVED',
        'INCREMENT_TIER_CHANGED', 'CATEGORY_CHANGED'
    ))
);

CREATE INDEX ix_audit_entity ON audit_logs (entity_type, entity_id, created_at DESC);
CREATE INDEX ix_audit_actor  ON audit_logs (actor_user_id, created_at DESC);
CREATE INDEX ix_audit_action ON audit_logs (action, created_at DESC);

-- =====================================================================
-- ŞİKAYETLER
-- =====================================================================

CREATE TABLE reports (
    id               UUID           PRIMARY KEY DEFAULT gen_random_uuid(),
    reporter_id      UUID           NOT NULL,
    listing_id       UUID           NOT NULL,
    reason_code      VARCHAR(32)    NOT NULL,
    description      VARCHAR(1000),
    status           VARCHAR(16)    NOT NULL DEFAULT 'OPEN',
    resolved_by      UUID,
    resolved_at      TIMESTAMPTZ,
    resolution_note  VARCHAR(500),
    created_at       TIMESTAMPTZ    NOT NULL DEFAULT now(),

    CONSTRAINT fk_reports_reporter FOREIGN KEY (reporter_id)
        REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT fk_reports_listing FOREIGN KEY (listing_id)
        REFERENCES listings (id) ON DELETE CASCADE,
    CONSTRAINT fk_reports_resolver FOREIGN KEY (resolved_by)
        REFERENCES users (id) ON DELETE SET NULL,

    -- Bir kullanıcı aynı ilanı bir kez şikayet edebilir
    CONSTRAINT uq_reports_reporter_listing UNIQUE (reporter_id, listing_id),

    CONSTRAINT ck_reports_reason CHECK (reason_code IN (
        'FAKE_LISTING', 'PROHIBITED_ITEM', 'MISLEADING_INFO',
        'OFFENSIVE_CONTENT', 'SUSPECTED_FRAUD', 'WRONG_CATEGORY', 'OTHER'
    )),
    CONSTRAINT ck_reports_status CHECK (status IN (
        'OPEN', 'IN_REVIEW', 'RESOLVED', 'DISMISSED'
    )),
    CONSTRAINT ck_reports_resolution CHECK (
        (status IN ('OPEN', 'IN_REVIEW')) = (resolved_at IS NULL)
    )
);

-- Moderasyon kuyruğu · kısmi index
CREATE INDEX ix_reports_open
    ON reports (created_at)
    WHERE status IN ('OPEN', 'IN_REVIEW');

CREATE INDEX ix_reports_listing ON reports (listing_id);

-- =====================================================================
-- KARŞILIKLI PUANLAMA (BR-N-006)
-- =====================================================================

CREATE TABLE user_ratings (
    id          UUID          PRIMARY KEY DEFAULT gen_random_uuid(),
    auction_id  UUID          NOT NULL,
    rater_id    UUID          NOT NULL,
    ratee_id    UUID          NOT NULL,
    score       SMALLINT      NOT NULL,
    comment     VARCHAR(500),
    created_at  TIMESTAMPTZ   NOT NULL DEFAULT now(),

    CONSTRAINT fk_ratings_auction FOREIGN KEY (auction_id)
        REFERENCES auctions (id) ON DELETE RESTRICT,
    CONSTRAINT fk_ratings_rater FOREIGN KEY (rater_id)
        REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT fk_ratings_ratee FOREIGN KEY (ratee_id)
        REFERENCES users (id) ON DELETE RESTRICT,

    -- Bir kişi bir artırmada bir kez puan verir
    CONSTRAINT uq_ratings_auction_rater UNIQUE (auction_id, rater_id),

    CONSTRAINT ck_ratings_score CHECK (score BETWEEN 1 AND 5),
    CONSTRAINT ck_ratings_not_self CHECK (rater_id <> ratee_id)
);

CREATE INDEX ix_ratings_ratee ON user_ratings (ratee_id, created_at DESC);

-- NOT: BR-N-006'daki "kapanıştan sonraki 30 gün" penceresi CHECK ile
-- ifade edilemez (kapanış zamanı başka tabloda ve zamanla değişen bir
-- karşılaştırma gerektirir). Servis katmanında denetlenir.

-- =====================================================================
-- İLETİŞİM BİLGİSİ İFŞA KAYDI (BR-N-004, BR-K-004)
-- ---------------------------------------------------------------------
-- Kullanıcı, kendi telefon numarasının KİME, NE ZAMAN, HANGİ İŞLEM
-- nedeniyle açıldığını sorgulayabilmelidir. Kişisel veri paylaşan bir
-- platform için yasal gerekliliktir ve teknik olarak tek satırlık maliyeti
-- vardır.
-- =====================================================================

CREATE TABLE contact_disclosures (
    id                UUID          PRIMARY KEY DEFAULT gen_random_uuid(),
    auction_id        UUID          NOT NULL,
    viewer_user_id    UUID          NOT NULL,   -- bilgiyi GÖREN
    subject_user_id   UUID          NOT NULL,   -- bilgisi AÇILAN
    disclosed_fields  VARCHAR(100)  NOT NULL,   -- 'PHONE,EMAIL'
    viewer_ip         INET,
    disclosed_at      TIMESTAMPTZ   NOT NULL DEFAULT now(),

    CONSTRAINT fk_disclosures_auction FOREIGN KEY (auction_id)
        REFERENCES auctions (id) ON DELETE RESTRICT,
    CONSTRAINT fk_disclosures_viewer FOREIGN KEY (viewer_user_id)
        REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT fk_disclosures_subject FOREIGN KEY (subject_user_id)
        REFERENCES users (id) ON DELETE RESTRICT,

    CONSTRAINT uq_disclosures UNIQUE (auction_id, viewer_user_id, subject_user_id),
    CONSTRAINT ck_disclosures_not_self CHECK (viewer_user_id <> subject_user_id)
);

-- "Benim bilgim kime açıldı?" sorgusu (KVKK bilgi talebi)
CREATE INDEX ix_disclosures_subject ON contact_disclosures (subject_user_id, disclosed_at DESC);

-- =====================================================================
-- Yorumlar
-- =====================================================================
COMMENT ON TABLE  outbox_events        IS 'BR-N-007 · Transactional Outbox. Teklif ile bildirim aynı transaction''da atomik bağlanır.';
COMMENT ON COLUMN outbox_events.id     IS 'BIGINT identity bilinçli: olaylar üretim sırasıyla yayınlanmalıdır.';
COMMENT ON TABLE  audit_logs           IS 'BR-S-006 · Kritik işlemlerin öncesi/sonrası kaydı. BR-K-005 uyarınca 2 yıl saklanır.';
COMMENT ON TABLE  contact_disclosures  IS 'BR-K-004 · KVKK · İletişim bilgisi ifşa izi.';
COMMENT ON TABLE  watchlist            IS 'BR-N-002 · Favoriler. Bileşik PK, ayrı id kolonu yok.';
