package com.gib.tiklasat.entity;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * İlçeler. Her ilçe bir ile (City) bağlıdır.
 * SQL: districts tablosu — PK GENERATED BY DEFAULT AS IDENTITY
 */
@Entity
@Table(name = "districts",
       uniqueConstraints = @UniqueConstraint(
           name = "uq_districts_city_name",
           columnNames = {"city_id", "name"}
       ))
@Getter
@Setter
@NoArgsConstructor
public class District {

    /**
     * Otomatik artan PK.
     * SQL: INTEGER GENERATED BY DEFAULT AS IDENTITY
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
    private Integer id;

    /**
     * Bu ilçenin bağlı olduğu il.
     * FetchType.LAZY: ilçeyi çektiğimizde il bilgisi hemen yüklenmez,
     * sadece erişildiğinde veritabanından çekilir. Performans için önemli.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "city_id", nullable = false,
                foreignKey = @ForeignKey(name = "fk_districts_city"))
    private City city;

    @Column(name = "name", nullable = false, length = 60)
    private String name;
}
